# ==============================================================================
# Merged Lakeflow Source: notion
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import (
    Any,
    Dict,
    Iterable,
    Iterator,
    List,
    Optional,
    Sequence,
    Tuple,
)
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/notion/notion.py
    ########################################################

    _TRUNCATION_THRESHOLD = 25

    # Property types Notion paginates on the page object.
    _PAGINATED_PROPERTY_TYPES = ("title", "rich_text", "relation", "people", "rollup")

    _DEFAULT_NOTION_VERSION = "2026-03-11"
    _DEFAULT_PAGE_SIZE = 100
    _DEFAULT_MAX_RECORDS_PER_BATCH = 200
    # Hard ceiling on how many items we will pull back for a single truncated
    # property, so one pathological relation cannot blow up a microbatch.
    _DEFAULT_MAX_PROPERTY_ITEMS = 1000
    # Depth limit for the recursive block-tree crawl.
    _DEFAULT_MAX_BLOCK_DEPTH = 5

    _MAX_RETRIES = 5
    _RETRIABLE_STATUS_CODES = (429, 500, 502, 503, 504)


    def _json_str(value: Any) -> Optional[str]:
        """Render a value as a string suitable for a ``MapType(String, String)`` cell.

        Notion nests objects arbitrarily (``cover.external.url``,
        ``parent.database_id``, …). Spark's string map cannot hold those, so
        non-scalar values are JSON-encoded and scalars are passed through as
        plain strings — no quotes, so ``parent["type"]`` reads as ``database_id``
        rather than ``"database_id"``.
        """
        if value is None:
            return None
        if isinstance(value, str):
            return value
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return str(value)
        return json.dumps(value, ensure_ascii=False, sort_keys=True)


    def _string_map(value: Any) -> Optional[Dict[str, Optional[str]]]:
        """Coerce a Notion sub-object into a flat ``{str: str}`` map."""
        if value is None:
            return None
        if not isinstance(value, dict):
            return {"value": _json_str(value)}
        return {k: _json_str(v) for k, v in value.items()}


    def _string_map_list(value: Any) -> Optional[List[Dict[str, Optional[str]]]]:
        """Coerce a list of Notion sub-objects into a list of flat string maps."""
        if value is None:
            return None
        if not isinstance(value, list):
            value = [value]
        return [_string_map(item) or {} for item in value]


    class NotionLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for Notion.

        Uses the plain (non-partitioned) ``LakeflowConnect`` path deliberately.
        Notion exposes no range-query filter — ``POST /v1/search`` can only be
        *sorted* by ``last_edited_time``, never bounded by it — so there is no
        way to split a read into independent, self-contained time windows for
        executors. Partitioning would degenerate into every executor replaying
        the same cursor walk.
        """

        def __init__(self, options: dict) -> None:
            super().__init__(options)
            self.api_token = options["api_token"]
            self.base_url = "https://api.notion.com/v1"
            self.notion_version = options.get("notion_version", _DEFAULT_NOTION_VERSION)
            self.headers = {
                "Authorization": f"Bearer {self.api_token}",
                "Notion-Version": self.notion_version,
                "Content-Type": "application/json",
            }
            # Cap cursors at init time so a Trigger.AvailableNow run never chases
            # data that arrives mid-run. The next trigger builds a fresh instance
            # with a newer cap and picks up the remainder.
            self._init_ts = datetime.now(timezone.utc).isoformat()

        # ------------------------------------------------------------------
        # Interface: tables, schemas, metadata
        # ------------------------------------------------------------------

        def list_tables(self) -> List[str]:
            return [
                "pages",
                "databases",
                "data_sources",
                "views",
                "blocks",
                "comments",
                "users",
                "file_uploads",
            ]

        def get_table_schema(self, table_name: str, table_options: Dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return _TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: Dict[str, str]) -> dict:
            self._validate_table(table_name)
            return dict(_TABLE_METADATA[table_name])

        def _validate_table(self, table_name: str) -> None:
            if table_name not in _TABLE_SCHEMAS:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {sorted(_TABLE_SCHEMAS)}"
                )

        # ------------------------------------------------------------------
        # Interface: reads
        # ------------------------------------------------------------------

        def read_table(
            self, table_name: str, start_offset: dict, table_options: Dict[str, str]
        ) -> Tuple[Iterator[dict], dict]:
            self._validate_table(table_name)

            if table_name == "users":
                return self._read_users(table_options)

            return self._read_incremental(table_name, start_offset or {}, table_options)

        def _read_incremental(
            self, table_name: str, start_offset: dict, table_options: Dict[str, str]
        ) -> Tuple[Iterator[dict], dict]:
            """Shared incremental driver for every CDC table.

            Notion has no server-side ``since`` filter, so the contract each
            ``_collect_*`` helper implements is: walk the source in *ascending*
            watermark order, drop anything at-or-below ``since``, drop anything
            above ``self._init_ts``, and stop once ``max_records`` rows are in
            hand. This method then derives the new offset from the last
            watermark actually consumed.

            Returning ``start_offset`` unchanged when nothing new was found is
            what terminates ``Trigger.AvailableNow``.
            """
            since = start_offset.get("cursor")
            if since and since >= self._init_ts:
                # Already caught up to the cap — skip the API calls entirely.
                return iter([]), start_offset

            max_records = int(
                table_options.get("max_records_per_batch", _DEFAULT_MAX_RECORDS_PER_BATCH)
            )

            collector = getattr(self, f"_collect_{table_name}")
            records, watermark = collector(since, max_records, table_options)

            if not records:
                return iter([]), start_offset

            end_offset = {"cursor": watermark}
            if end_offset == start_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        # ------------------------------------------------------------------
        # HTTP
        # ------------------------------------------------------------------

        def _request(self, method: str, path: str, **kwargs) -> requests.Response:
            """Issue an API request, retrying on 429, 5xx, and connection-level
            failures (timeouts, dropped connections) with backoff.

            A read/connect timeout raises inside ``requests`` before a response
            ever exists, so it can't be handled by checking ``resp.status_code``
            like the retriable-status path below -- it has to be caught
            separately, or one transient network blip kills the whole streaming
            query instead of just costing a retry.
            """
            kwargs.setdefault("timeout", 30)
            backoff = 1.0
            resp = None
            last_error: Optional[requests.exceptions.RequestException] = None

            for attempt in range(_MAX_RETRIES):
                url = f"{self.base_url}/{path.lstrip('/')}"
                try:
                    if method == "GET":
                        resp = requests.get(url, headers=self.headers, **kwargs)
                    elif method == "POST":
                        resp = requests.post(url, headers=self.headers, **kwargs)
                    else:
                        raise ValueError(f"Unsupported HTTP method: {method}")
                except requests.exceptions.RequestException as exc:
                    last_error = exc
                    resp = None
                    if attempt < _MAX_RETRIES - 1:
                        time.sleep(backoff)
                        backoff *= 2
                    continue

                if resp.status_code not in _RETRIABLE_STATUS_CODES:
                    return resp

                if attempt < _MAX_RETRIES - 1:
                    # Notion sends Retry-After on 429; fall back to exponential
                    # backoff for 5xx.
                    delay = resp.headers.get("retry-after")
                    time.sleep(float(delay) if delay else backoff)
                    backoff *= 2

            if resp is None and last_error is not None:
                raise last_error
            return resp

        def _get_json(
            self, path: str, params: Optional[dict] = None, *, ignore_statuses: Tuple[int, ...] = ()
        ) -> Optional[dict]:
            """GET one object. Returns ``None`` for 403/404 (not shared with the
            integration) or any status in ``ignore_statuses`` rather than aborting
            the whole read."""
            resp = self._request("GET", path, params=params or {})
            if resp.status_code in (403, 404) or resp.status_code in ignore_statuses:
                return None
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Notion API error on GET /{path}: {resp.status_code} {resp.text}"
                )
            return resp.json()

        def _paginate(
            self, method: str, path: str, *, params: Optional[dict] = None,
            body: Optional[dict] = None, page_size: int = _DEFAULT_PAGE_SIZE,
        ) -> Iterator[dict]:
            """Walk a Notion cursor-paginated list endpoint, yielding results.

            A 403/404 mid-walk means the object stopped being shared with the
            integration; treat it as end-of-list rather than failing the read.
            """
            start_cursor: Optional[str] = None
            while True:
                if method == "GET":
                    call_params = dict(params or {})
                    call_params["page_size"] = page_size
                    if start_cursor:
                        call_params["start_cursor"] = start_cursor
                    resp = self._request("GET", path, params=call_params)
                else:
                    call_body = dict(body or {})
                    call_body["page_size"] = page_size
                    if start_cursor:
                        call_body["start_cursor"] = start_cursor
                    resp = self._request("POST", path, json=call_body)

                if resp.status_code in (403, 404):
                    return
                if resp.status_code != 200:
                    raise RuntimeError(
                        f"Notion API error on {method} /{path}: "
                        f"{resp.status_code} {resp.text}"
                    )

                payload = resp.json()
                results = payload.get("results") or []
                for item in results:
                    yield item

                start_cursor = payload.get("next_cursor")
                if not payload.get("has_more") or not start_cursor:
                    return

        # ------------------------------------------------------------------
        # Root enumeration
        # ------------------------------------------------------------------

        def _iter_search(self, object_type: str) -> Iterator[dict]:
            """Enumerate ``page`` or ``data_source`` objects, oldest edit first.

            ``POST /v1/search`` accepts no time filter, only a sort direction, so
            an incremental read has to re-walk from the start of the sort and
            skip client-side. Ascending order is what makes that skip safe: once
            we pass the previous watermark, every remaining record is new.
            """
            body = {
                "filter": {"property": "object", "value": object_type},
                "sort": {"direction": "ascending", "timestamp": "last_edited_time"},
            }
            yield from self._paginate("POST", "search", body=body)

        def _iter_new(
            self, records: Iterable[dict], since: Optional[str], cursor_field: str
        ) -> Iterator[Tuple[dict, str]]:
            """Yield ``(record, watermark)`` for records inside ``(since, init_ts]``.

            Ascending input is assumed, so the first record past ``_init_ts``
            ends the walk.
            """
            for record in records:
                watermark = record.get(cursor_field)
                if not watermark:
                    continue
                if watermark > self._init_ts:
                    return
                if since and watermark <= since:
                    continue
                yield record, watermark

        # ------------------------------------------------------------------
        # Per-table collectors
        #
        # Each returns ``(records, watermark)``. The watermark is the offset
        # value to checkpoint; it is not necessarily the emitted rows' cursor
        # field (see ``_collect_blocks``).
        # ------------------------------------------------------------------

        def _collect_pages(
            self, since: Optional[str], max_records: int, table_options: Dict[str, str]
        ) -> Tuple[List[dict], Optional[str]]:
            resolve = table_options.get("resolve_truncated_properties", "true").lower() != "false"
            max_items = int(table_options.get("max_property_items", _DEFAULT_MAX_PROPERTY_ITEMS))

            records: List[dict] = []
            watermark: Optional[str] = None
            for page, mark in self._iter_new(
                self._iter_search("page"), since, "last_edited_time"
            ):
                records.append(self._flatten_page(page, resolve=resolve, max_items=max_items))
                watermark = mark
                if len(records) >= max_records:
                    break
            return records, watermark

        def _collect_data_sources(
            self, since: Optional[str], max_records: int, table_options: Dict[str, str]
        ) -> Tuple[List[dict], Optional[str]]:
            records: List[dict] = []
            watermark: Optional[str] = None
            for source, mark in self._iter_new(
                self._iter_search("data_source"), since, "last_edited_time"
            ):
                records.append(self._flatten_data_source(source))
                watermark = mark
                if len(records) >= max_records:
                    break
            return records, watermark

        def _collect_databases(
            self, since: Optional[str], max_records: int, table_options: Dict[str, str]
        ) -> Tuple[List[dict], Optional[str]]:
            """Databases are not searchable — ``POST /v1/search`` only accepts
            ``page`` and ``data_source``. Reach them through the data sources
            they own (``data_source.parent.database_id``), then hydrate each with
            ``GET /v1/databases/{id}``.

            The offset watermark stays on the *data source* edit time, since
            that is the ordered sequence we walk.
            """
            records: List[dict] = []
            watermark: Optional[str] = None
            seen: set = set()

            for source, mark in self._iter_new(
                self._iter_search("data_source"), since, "last_edited_time"
            ):
                parent = source.get("parent") or {}
                database_id = parent.get("database_id")
                watermark = mark
                if not database_id or database_id in seen:
                    continue
                seen.add(database_id)

                database = self._get_json(f"databases/{database_id}")
                if database:
                    records.append(self._flatten_database(database))
                if len(records) >= max_records:
                    break
            return records, watermark

        def _collect_views(
            self, since: Optional[str], max_records: int, table_options: Dict[str, str]
        ) -> Tuple[List[dict], Optional[str]]:
            """``GET /v1/views`` requires a ``data_source_id`` (or ``database_id``)
            and returns *partial* view refs — id and type only. Each ref is then
            hydrated with ``GET /v1/views/{view_id}``.

            Watermark is the owning data source's edit time: Notion bumps that
            whenever a view on it is added or reconfigured.
            """
            records: List[dict] = []
            watermark: Optional[str] = None
            seen: set = set()

            for source, mark in self._iter_new(
                self._iter_search("data_source"), since, "last_edited_time"
            ):
                watermark = mark
                data_source_id = source.get("id")
                if not data_source_id:
                    continue

                for ref in self._paginate(
                    "GET", "views", params={"data_source_id": data_source_id}
                ):
                    view_id = ref.get("id")
                    if not view_id or view_id in seen:
                        continue
                    seen.add(view_id)

                    view = ref
                    # A partial ref has no name/created_time — hydrate it. Some
                    # view types (e.g. "feed") 400 on the single-view GET even
                    # though they list fine — Notion just doesn't support
                    # retrieving them individually. The id came straight from the
                    # list endpoint, so a 400 here means an unsupported view
                    # type, not a malformed request; fall back to the partial ref
                    # rather than failing the whole read over one view.
                    if "name" not in ref or "created_time" not in ref:
                        hydrated = self._get_json(f"views/{view_id}", ignore_statuses=(400,))
                        if hydrated:
                            view = hydrated
                    records.append(self._flatten_view(view, data_source_id))

                if len(records) >= max_records:
                    break
            return records, watermark

        def _collect_blocks(
            self, since: Optional[str], max_records: int, table_options: Dict[str, str]
        ) -> Tuple[List[dict], Optional[str]]:
            """Crawl the block tree beneath every page whose edit time is new.

            The offset watermark is the *parent page's* ``last_edited_time``, not
            the block's. Notion bumps a page's edit time whenever any block on it
            changes, so gating the crawl on the page watermark is both complete
            and monotonic — whereas individual block timestamps are not ordered
            with respect to each other across pages, and would make the offset
            jump backwards. ``cursor_field`` in table metadata remains the
            block's own ``last_edited_time``, which is the right key for the
            downstream CDC merge.
            """
            max_depth = int(table_options.get("max_block_depth", _DEFAULT_MAX_BLOCK_DEPTH))

            records: List[dict] = []
            watermark: Optional[str] = None
            for page, mark in self._iter_new(
                self._iter_search("page"), since, "last_edited_time"
            ):
                watermark = mark
                page_id = page.get("id")
                if not page_id:
                    continue
                for block in self._crawl_blocks(page_id, depth=max_depth):
                    records.append(self._flatten_block(block))
                if len(records) >= max_records:
                    break
            return records, watermark

        def _crawl_blocks(self, block_id: str, depth: int) -> Iterator[dict]:
            """Depth-first walk of ``GET /v1/blocks/{id}/children``."""
            if depth <= 0:
                return
            for block in self._paginate("GET", f"blocks/{block_id}/children"):
                yield block
                if block.get("has_children") and block.get("id"):
                    yield from self._crawl_blocks(block["id"], depth - 1)

        def _collect_comments(
            self, since: Optional[str], max_records: int, table_options: Dict[str, str]
        ) -> Tuple[List[dict], Optional[str]]:
            """Comments are only reachable per-block. Walk new pages and read the
            comment thread hanging off each. Watermark is the page edit time, for
            the same reason as ``_collect_blocks``.
            """
            records: List[dict] = []
            watermark: Optional[str] = None
            for page, mark in self._iter_new(
                self._iter_search("page"), since, "last_edited_time"
            ):
                watermark = mark
                page_id = page.get("id")
                if not page_id:
                    continue
                for comment in self._paginate(
                    "GET", "comments", params={"block_id": page_id}
                ):
                    records.append(self._flatten_comment(comment))
                if len(records) >= max_records:
                    break
            return records, watermark

        def _collect_file_uploads(
            self, since: Optional[str], max_records: int, table_options: Dict[str, str]
        ) -> Tuple[List[dict], Optional[str]]:
            """``GET /v1/file_uploads`` enumerates every upload the integration
            owns, so unlike most "attachment" APIs there is no need to hydrate
            ids scraped out of blocks one at a time.

            The endpoint has no time filter and no documented sort order, so we
            buffer the listing and sort by ``last_edited_time`` ourselves before
            applying the watermark.
            """
            params = {}
            status = table_options.get("file_upload_status")
            if status:
                params["status"] = status

            uploads = list(self._paginate("GET", "file_uploads", params=params))
            uploads.sort(key=lambda u: u.get("last_edited_time") or "")

            records: List[dict] = []
            watermark: Optional[str] = None
            for upload, mark in self._iter_new(uploads, since, "last_edited_time"):
                records.append(self._flatten_file_upload(upload))
                watermark = mark
                if len(records) >= max_records:
                    break
            return records, watermark

        def _read_users(self, table_options: Dict[str, str]) -> Tuple[Iterator[dict], dict]:
            """Full snapshot of ``GET /v1/users``."""
            records = [self._flatten_user(u) for u in self._paginate("GET", "users")]
            return iter(records), {}

        # ------------------------------------------------------------------
        # Page property truncation
        # ------------------------------------------------------------------

        @staticmethod
        def _is_truncated(prop: Any) -> bool:
            """Detect a page property that the page object returned incomplete.

            Notion signals this three different ways depending on type, and
            sometimes not at all:

            * ``has_more: true`` on the property (relations, people, rich text)
            * ``rollup.type == "incomplete"`` for rollups needing more
              aggregation pages
            * silently, by capping the array at 25 entries

            The last case is why we also treat "exactly 25 items" as suspect and
            re-resolve; a false positive costs one extra API call, a false
            negative silently drops data.
            """
            if not isinstance(prop, dict):
                return False
            if prop.get("has_more") is True:
                return True

            prop_type = prop.get("type")
            if prop_type == "rollup":
                rollup = prop.get("rollup")
                if isinstance(rollup, dict) and rollup.get("type") == "incomplete":
                    return True

            if prop_type in _PAGINATED_PROPERTY_TYPES:
                value = prop.get(prop_type)
                if isinstance(value, list) and len(value) >= _TRUNCATION_THRESHOLD:
                    return True
            return False

        def _resolve_property(
            self, page_id: str, property_id: str, prop: dict, max_items: int
        ) -> dict:
            """Re-fetch a truncated property via
            ``GET /v1/pages/{page_id}/properties/{property_id}``.

            The endpoint returns a paginated list of ``property_item`` objects;
            we unwrap each one back into the shape the page object *would* have
            had, so downstream consumers see a single consistent representation
            rather than two.
            """
            prop_type = prop.get("type")
            items: List[Any] = []
            rollup_aggregate: Optional[dict] = None
            truncated = False

            for item in self._paginate(
                "GET", f"pages/{page_id}/properties/{property_id}"
            ):
                if len(items) >= max_items:
                    truncated = True
                    break
                item_type = item.get("type")
                if item_type == "rollup":
                    # The aggregate lives on the wrapper, not the items; the
                    # items themselves are the rolled-up values.
                    rollup_aggregate = item.get("rollup")
                    continue
                items.append(item.get(item_type, item) if item_type else item)

            if not items and rollup_aggregate is None:
                # Nothing came back (403/404, or an unsupported property type) —
                # keep the truncated page-object value rather than blanking it.
                return prop

            resolved = dict(prop)
            if prop_type == "rollup" and rollup_aggregate is not None:
                resolved["rollup"] = rollup_aggregate
                resolved["results"] = items
            elif prop_type:
                resolved[prop_type] = items
            resolved["has_more"] = truncated
            return resolved

        def _resolve_properties(
            self, page_id: str, properties: dict, max_items: int
        ) -> Tuple[Dict[str, Any], List[str]]:
            """Resolve every truncated property on a page.

            Returns ``(properties, names_of_resolved_properties)``.
            """
            resolved: Dict[str, Any] = {}
            touched: List[str] = []
            for name, prop in (properties or {}).items():
                if self._is_truncated(prop) and isinstance(prop, dict) and prop.get("id"):
                    resolved[name] = self._resolve_property(
                        page_id, prop["id"], prop, max_items
                    )
                    touched.append(name)
                else:
                    resolved[name] = prop
            return resolved, touched

        # ------------------------------------------------------------------
        # Flatteners — map a raw Notion object onto its table schema
        # ------------------------------------------------------------------

        def _flatten_page(self, page: dict, *, resolve: bool, max_items: int) -> dict:
            properties = page.get("properties") or {}
            truncated: List[str] = []
            if resolve and page.get("id"):
                properties, truncated = self._resolve_properties(
                    page["id"], properties, max_items
                )

            return {
                "id": page.get("id"),
                "url": page.get("url"),
                "public_url": page.get("public_url"),
                "in_trash": _coalesce_trash(page),
                "is_locked": page.get("is_locked"),
                "created_time": page.get("created_time"),
                "last_edited_time": page.get("last_edited_time"),
                "created_by": _string_map(page.get("created_by")),
                "last_edited_by": _string_map(page.get("last_edited_by")),
                "cover": _string_map(page.get("cover")),
                "icon": _string_map(page.get("icon")),
                "parent": _string_map(page.get("parent")),
                "properties": {k: _json_str(v) for k, v in properties.items()},
                "truncated_properties": truncated,
                "request_id": page.get("request_id"),
            }

        def _flatten_data_source(self, source: dict) -> dict:
            return {
                "id": source.get("id"),
                "url": source.get("url"),
                "name": source.get("name"),
                "title": _string_map_list(source.get("title")),
                "description": _string_map_list(source.get("description")),
                "is_inline": source.get("is_inline"),
                "in_trash": _coalesce_trash(source),
                "database_parent": _string_map(source.get("database_parent")),
                "created_time": source.get("created_time"),
                "last_edited_time": source.get("last_edited_time"),
                "created_by": _string_map(source.get("created_by")),
                "last_edited_by": _string_map(source.get("last_edited_by")),
                "parent": _string_map(source.get("parent")),
                "properties": {
                    k: _json_str(v) for k, v in (source.get("properties") or {}).items()
                },
                "request_id": source.get("request_id"),
            }

        def _flatten_database(self, database: dict) -> dict:
            data_sources = database.get("data_sources") or []
            return {
                "id": database.get("id"),
                "url": database.get("url"),
                "public_url": database.get("public_url"),
                "title": _string_map_list(database.get("title")),
                "description": _string_map_list(database.get("description")),
                "is_inline": database.get("is_inline"),
                "is_locked": database.get("is_locked"),
                "in_trash": _coalesce_trash(database),
                "created_time": database.get("created_time"),
                "last_edited_time": database.get("last_edited_time"),
                "created_by": _string_map(database.get("created_by")),
                "last_edited_by": _string_map(database.get("last_edited_by")),
                "cover": _string_map(database.get("cover")),
                "icon": _string_map(database.get("icon")),
                "parent": _string_map(database.get("parent")),
                "data_sources": _string_map_list(data_sources),
                "data_source_ids": [
                    ds.get("id") for ds in data_sources if isinstance(ds, dict) and ds.get("id")
                ],
                "request_id": database.get("request_id"),
            }

        def _flatten_view(self, view: dict, data_source_id: Optional[str]) -> dict:
            return {
                "id": view.get("id"),
                "name": view.get("name"),
                "type": view.get("type"),
                "url": view.get("url"),
                "data_source_id": view.get("data_source_id") or data_source_id,
                "parent": _string_map(view.get("parent")),
                "created_time": view.get("created_time"),
                "last_edited_time": view.get("last_edited_time"),
                "created_by": _string_map(view.get("created_by")),
                "last_edited_by": _string_map(view.get("last_edited_by")),
                "filter": _json_str(view.get("filter")),
                "sorts": _json_str(view.get("sorts")),
                "quick_filters": _json_str(view.get("quick_filters")),
                "configuration": _json_str(view.get("configuration")),
                "dashboard_view_id": view.get("dashboard_view_id"),
            }

        def _flatten_block(self, block: dict) -> dict:
            row = {
                "id": block.get("id"),
                "type": block.get("type"),
                "created_time": block.get("created_time"),
                "last_edited_time": block.get("last_edited_time"),
                "created_by": _string_map(block.get("created_by")),
                "last_edited_by": _string_map(block.get("last_edited_by")),
                "has_children": block.get("has_children"),
                "in_trash": _coalesce_trash(block),
                "parent": _string_map(block.get("parent")),
            }
            for block_type in _BLOCK_TYPE_FIELDS:
                row[block_type] = _string_map(block.get(block_type))
            return row

        def _flatten_comment(self, comment: dict) -> dict:
            return {
                "id": comment.get("id"),
                "parent": _string_map(comment.get("parent")),
                "discussion_id": comment.get("discussion_id"),
                "created_by": _string_map(comment.get("created_by")),
                "created_time": comment.get("created_time"),
                "last_edited_time": comment.get("last_edited_time"),
                "display_name": _string_map(comment.get("display_name")),
                "rich_text": _string_map_list(comment.get("rich_text")),
                "attachments": _string_map_list(comment.get("attachments")),
            }

        def _flatten_user(self, user: dict) -> dict:
            return {
                "id": user.get("id"),
                "name": user.get("name"),
                "avatar_url": user.get("avatar_url"),
                "type": user.get("type"),
                "person": _string_map(user.get("person")),
                "bot": _string_map(user.get("bot")),
            }

        def _flatten_file_upload(self, upload: dict) -> dict:
            content_length = upload.get("content_length")
            return {
                "id": upload.get("id"),
                "filename": upload.get("filename"),
                "content_type": upload.get("content_type"),
                "content_length": int(content_length) if content_length is not None else None,
                "status": upload.get("status"),
                "mode": upload.get("mode"),
                "expiry_time": upload.get("expiry_time"),
                "created_time": upload.get("created_time"),
                "last_edited_time": upload.get("last_edited_time"),
                "created_by": _string_map(upload.get("created_by")),
                "file_import_result": _string_map(upload.get("file_import_result")),
                "number_of_parts": _string_map(upload.get("number_of_parts")),
            }


    def _coalesce_trash(obj: dict) -> Optional[bool]:
        """Read the trash flag under either name.

        ``2026-03-11`` renamed ``archived`` to ``in_trash``. Reading both keeps
        the connector working if a user pins ``notion_version`` back to
        ``2025-09-03``.
        """
        if "in_trash" in obj:
            return obj.get("in_trash")
        return obj.get("archived")


    # ----------------------------------------------------------------------
    # Block-type union
    #
    # One column per Notion block type, each holding that type's content
    # object. ``meeting_notes`` is the 2026-03-11 name for what earlier
    # versions called ``transcription``; both are listed so a pinned-back
    # ``notion_version`` still populates a column.
    # ----------------------------------------------------------------------

    _BLOCK_TYPE_FIELDS = (
        "audio",
        "bookmark",
        "breadcrumb",
        "bulleted_list_item",
        "callout",
        "child_database",
        "child_page",
        "code",
        "column",
        "column_list",
        "divider",
        "embed",
        "equation",
        "file",
        "heading_1",
        "heading_2",
        "heading_3",
        "heading_4",
        "image",
        "link_preview",
        "link_to_page",
        "meeting_notes",
        "numbered_list_item",
        "paragraph",
        "pdf",
        "quote",
        "synced_block",
        "table",
        "table_of_contents",
        "table_row",
        "tab",
        "template",
        "to_do",
        "toggle",
        "transcription",
        "unsupported",
        "video",
    )


    def _string_map_field(name: str) -> StructField:
        return StructField(name, MapType(StringType(), StringType()))


    def _string_map_list_field(name: str) -> StructField:
        return StructField(name, ArrayType(MapType(StringType(), StringType())))


    _TABLE_SCHEMAS: Dict[str, StructType] = {
        "pages": StructType(
            [
                StructField("id", StringType()),
                StructField("url", StringType()),
                StructField("public_url", StringType()),
                StructField("in_trash", BooleanType()),
                StructField("is_locked", BooleanType()),
                StructField("created_time", StringType()),
                StructField("last_edited_time", StringType()),
                _string_map_field("created_by"),
                _string_map_field("last_edited_by"),
                _string_map_field("cover"),
                _string_map_field("icon"),
                _string_map_field("parent"),
                # Property values are JSON-encoded: Notion property values are
                # arbitrarily nested (a relation is an array of objects, a rollup
                # wraps an aggregate) and no flat Spark map can hold them.
                # Truncated properties are resolved before encoding, so what
                # lands here is always the *complete* value.
                StructField("properties", MapType(StringType(), StringType())),
                # Names of the properties that came back truncated on the page
                # object and were re-fetched. Empty for the common case.
                StructField("truncated_properties", ArrayType(StringType())),
                StructField("request_id", StringType()),
            ]
        ),
        "databases": StructType(
            [
                StructField("id", StringType()),
                StructField("url", StringType()),
                StructField("public_url", StringType()),
                _string_map_list_field("title"),
                _string_map_list_field("description"),
                StructField("is_inline", BooleanType()),
                StructField("is_locked", BooleanType()),
                StructField("in_trash", BooleanType()),
                StructField("created_time", StringType()),
                StructField("last_edited_time", StringType()),
                _string_map_field("created_by"),
                _string_map_field("last_edited_by"),
                _string_map_field("cover"),
                _string_map_field("icon"),
                _string_map_field("parent"),
                _string_map_list_field("data_sources"),
                StructField("data_source_ids", ArrayType(StringType())),
                StructField("request_id", StringType()),
            ]
        ),
        "data_sources": StructType(
            [
                StructField("id", StringType()),
                StructField("url", StringType()),
                StructField("name", StringType()),
                _string_map_list_field("title"),
                _string_map_list_field("description"),
                StructField("is_inline", BooleanType()),
                StructField("in_trash", BooleanType()),
                _string_map_field("database_parent"),
                StructField("created_time", StringType()),
                StructField("last_edited_time", StringType()),
                _string_map_field("created_by"),
                _string_map_field("last_edited_by"),
                _string_map_field("parent"),
                StructField("properties", MapType(StringType(), StringType())),
                StructField("request_id", StringType()),
            ]
        ),
        "views": StructType(
            [
                StructField("id", StringType()),
                StructField("name", StringType()),
                StructField("type", StringType()),
                StructField("url", StringType()),
                StructField("data_source_id", StringType()),
                _string_map_field("parent"),
                StructField("created_time", StringType()),
                StructField("last_edited_time", StringType()),
                _string_map_field("created_by"),
                _string_map_field("last_edited_by"),
                StructField("filter", StringType()),
                StructField("sorts", StringType()),
                StructField("quick_filters", StringType()),
                StructField("configuration", StringType()),
                StructField("dashboard_view_id", StringType()),
            ]
        ),
        "blocks": StructType(
            [
                StructField("id", StringType()),
                StructField("type", StringType()),
                StructField("created_time", StringType()),
                StructField("last_edited_time", StringType()),
                _string_map_field("created_by"),
                _string_map_field("last_edited_by"),
                StructField("has_children", BooleanType()),
                StructField("in_trash", BooleanType()),
                _string_map_field("parent"),
            ]
            + [_string_map_field(name) for name in _BLOCK_TYPE_FIELDS]
        ),
        "comments": StructType(
            [
                StructField("id", StringType()),
                _string_map_field("parent"),
                StructField("discussion_id", StringType()),
                _string_map_field("created_by"),
                StructField("created_time", StringType()),
                StructField("last_edited_time", StringType()),
                _string_map_field("display_name"),
                _string_map_list_field("rich_text"),
                _string_map_list_field("attachments"),
            ]
        ),
        "users": StructType(
            [
                StructField("id", StringType()),
                StructField("name", StringType()),
                StructField("avatar_url", StringType()),
                StructField("type", StringType()),
                _string_map_field("person"),
                _string_map_field("bot"),
            ]
        ),
        "file_uploads": StructType(
            [
                StructField("id", StringType()),
                StructField("filename", StringType()),
                StructField("content_type", StringType()),
                StructField("content_length", LongType()),
                StructField("status", StringType()),
                StructField("mode", StringType()),
                StructField("expiry_time", StringType()),
                StructField("created_time", StringType()),
                StructField("last_edited_time", StringType()),
                _string_map_field("created_by"),
                _string_map_field("file_import_result"),
                _string_map_field("number_of_parts"),
            ]
        ),
    }


    _TABLE_METADATA: Dict[str, dict] = {
        "pages": {
            "primary_keys": ["id"],
            "cursor_field": "last_edited_time",
            "ingestion_type": "cdc",
        },
        "databases": {
            "primary_keys": ["id"],
            "cursor_field": "last_edited_time",
            "ingestion_type": "cdc",
        },
        "data_sources": {
            "primary_keys": ["id"],
            "cursor_field": "last_edited_time",
            "ingestion_type": "cdc",
        },
        "views": {
            "primary_keys": ["id"],
            "cursor_field": "last_edited_time",
            "ingestion_type": "cdc",
        },
        "blocks": {
            "primary_keys": ["id"],
            "cursor_field": "last_edited_time",
            "ingestion_type": "cdc",
        },
        "comments": {
            "primary_keys": ["id"],
            "cursor_field": "last_edited_time",
            "ingestion_type": "cdc",
        },
        "users": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "file_uploads": {
            "primary_keys": ["id"],
            "cursor_field": "last_edited_time",
            "ingestion_type": "cdc",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = NotionLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
